name: Scanner

on: workflow_dispatch # manual trigger

jobs:
  nuclei-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      # Install golang
      - name: Setup golang
        uses: actions/setup-go@v2
        with:
          go-version: '^1.17.4'

      - name: Setup go tools
        run: |
          go version
          GO111MODULE=on go install github.com/projectdiscovery/nuclei/v2/cmd/nuclei@latest
      
      - name: Run nuclei
        run: nuclei -u ${{env.TARGET_URL}} -o reports/nuclei/$(echo ${{env.TARGET_URL}} | awk -F[/:] '{print $4}')_output.txt -stats

  nuclei-scan-list:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      # Install golang
      - name: Setup golang
        uses: actions/setup-go@v2
        with:
          go-version: '^1.17.4'

      - name: Setup go tools
        run: |
          go version
          GO111MODULE=on go install github.com/projectdiscovery/nuclei/v2/cmd/nuclei@latest
      
      - name: Run nuclei
        run: nuclei -l reports/httpx/${{env.TARGET_DOMAIN}}_subdomains_httpx.txt -o reports/nuclei/${{env.TARGET_DOMAIN}}_output.txt -stats

  subfinder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      # Install golang
      - name: Setup golang
        uses: actions/setup-go@v5
        with:
          go-version: '^1.21'

      - name: Setup go tools
        run: |
          go version
          GO111MODULE=on go install -v github.com/projectdiscovery/subfinder/v2/cmd/subfinder@latest
      
      - name: Run Subfinder
        run: subfinder -silent -d ${{env.TARGET_DOMAIN}} -o reports/subfinder/${{env.TARGET_DOMAIN}}_subfinder.txt

# you can add more tools 
