name: Scanner

on: workflow_dispatch #manual trigger

jobs:

  nuclei_scan:
    runs-on: ubuntu-latest
    container:
      image: kotireddytest1/nuclei-scanner-only:v2.5.3
    steps:
      - name: Nuclei Scan
        run: |
          git -C /nuclei_scan/nuclei-templates pull
          /nuclei_scan/nuclei -u ${{env.TARGET_URL}} -t /nuclei_scan/nuclei-templates/ -o reports/nuclei/$(echo ${{env.TARGET_URL}} | awk -F[/:] '{print $4}')_output.txt -stats

  gobuster_scan:
    runs-on: ubuntu-latest
    container:
      image: kotireddytest1/gobuster-scanner-only:v3.1.0
    steps:
      - name: Gobuster Scan
        run: |
          /gobuster_scan/gobuster dir -u ${{env.TARGET_URL}} -k -b 400,403,404,429 -e -t 5 -o reports/gobuster/$(echo ${{env.TARGET_URL}} | awk -F[/:] '{print $4}')_quickhits.txt -w wordlist/quickhits.txt --wildcard
          /gobuster_scan/gobuster dir -u ${{env.TARGET_URL}} -k -b 400,403,404,429 -e -t 5 -o reports/gobuster/$(echo ${{env.TARGET_URL}} | awk -F[/:] '{print $4}')_web-content-1.txt -w wordlist/web-content-1.txt --wildcard
          /gobuster_scan/gobuster dir -u ${{env.TARGET_URL}} -k -b 400,403,404,429 -e -t 5 -o reports/gobuster/$(echo ${{env.TARGET_URL}} | awk -F[/:] '{print $4}')_web-content-2.txt -w wordlist/web-content-2.txt --wildcard

  nmap_scan:
    runs-on: ubuntu-latest
    steps:
      - id: set_env
        run: |
          export TARGET_DOMAIN=$(echo ${{env.TARGET_URL}} | awk -F[/:] '{print $4}')
          echo "::set-output name=TARGET_DOMAIN::${TARGET_DOMAIN}"
        outputs: 
          TARGET_DOMAIN::${{steps.set_env.outputs.TARGET_DOMAIN}}
      
      - uses: "MTES-MCT/nmap-action@main"
        with:
          host: ${{steps.set_env.outputs.TARGET_DOMAIN}}
          outputDir: 'reports/nmap/${{steps.set_env.outputs.TARGET_DOMAIN}}'
          outputFile: 'nmapvuln.json'
          raw: true
          withVulnerabilities: true


# zap tool action
      # - name: ZAP Scan
      #   uses: zaproxy/action-full-scan@v0.3.0
      #   with:
      #     target: ${{env.TARGET_URL}}



